# docker-compose.yml (for local development)
services:
  app:
    build: 
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FIREBASE_APP_ID=<firebase-app-id>
      - PRIVATE_KEY_FILE=<private-key-filename>
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev     

